<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Traitement d&#39;erreurs on Cours de C&#43;&#43; - Niveau Master</title>
    <link>https://laefy.github.io/CPP_Learning/chapter8/</link>
    <description>Recent content in Traitement d&#39;erreurs on Cours de C&#43;&#43; - Niveau Master</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language><atom:link href="https://laefy.github.io/CPP_Learning/chapter8/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>Assertions</title>
      <link>https://laefy.github.io/CPP_Learning/chapter8/1-assertions/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>https://laefy.github.io/CPP_Learning/chapter8/1-assertions/</guid>
      <description>Types d&amp;rsquo;erreurs Lorsqu&amp;rsquo;une erreur se produit dans un logiciel, il s&amp;rsquo;agit soit d&amp;rsquo;une erreur de programmation, soit d&amp;rsquo;une erreur d&amp;rsquo;utilisation du logiciel.
Voici quelques exemples :
 Un pointeur null a √©t√© d√©r√©f√©renc√© : erreur de programmation. Le programme a demand√© √† l&amp;rsquo;utilisateur de rentrer une image, mais celui-ci a fournit un fichier texte : erreur d&amp;rsquo;utilisation. On a √©crit dans la case array.size() de array : erreur de programmation.</description>
    </item>
    
    <item>
      <title>Exceptions</title>
      <link>https://laefy.github.io/CPP_Learning/chapter8/2-exceptions/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>https://laefy.github.io/CPP_Learning/chapter8/2-exceptions/</guid>
      <description>Qu&amp;rsquo;est-ce qu&amp;rsquo;une exception ? En C++, une exception sert √† interrompre le flot classique d&amp;rsquo;ex√©cution du programme lorsqu&amp;rsquo;un √©v√©nement particulier se produit. Lorsqu&amp;rsquo;une exception est lanc√©e, on sort du bloc courant, et on remonte la callstack autant que n√©cessaire, jusqu&amp;rsquo;√† atteindre un bloc capable de traiter l&amp;rsquo;exception.
C&amp;rsquo;est donc un m√©canisme extr√™mement utilis√© pour le traitement des erreurs (autant de programmation que d&amp;rsquo;utilisation), puisque l&amp;rsquo;erreur est remont√©e automatiquement jusqu&amp;rsquo;√† l&amp;rsquo;endroit qui peut la traiter, sans avoir besoin de toucher au code des fonctions interm√©diaires.</description>
    </item>
    
    <item>
      <title>Questionnaire !</title>
      <link>https://laefy.github.io/CPP_Learning/chapter8/test/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>https://laefy.github.io/CPP_Learning/chapter8/test/</guid>
      <description>C&amp;rsquo;est l&amp;rsquo;heure du test ! N&amp;rsquo;oubliez pas que vous pouvez utiliser Godbolt pour compiler et tester des petits bouts de code.
Bon courage √† vous üôÇ
 function updateTestSubject() {let name = document.querySelector(&#39;#testinput[name=&#34;name&#34;]&#39;).value;document.querySelector(&#39;#testinput[name=&#34;_subject&#34;]&#39;).value = &#34;[C++][Chapitre 8] &#34; + name + &#34;, retour sur ton questionnaire&#34;;}updateQuestionFormSubject();Vous √™tes :Votre adresse mail :Votre groupe :Initiaux 1Initiaux 2Alternants1- A quoi sert une assertion ?</description>
    </item>
    
    <item>
      <title>Merci !</title>
      <link>https://laefy.github.io/CPP_Learning/chapter8/test_done/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>https://laefy.github.io/CPP_Learning/chapter8/test_done/</guid>
      <description>Vos r√©ponses nous ont bien √©t√© communiqu√©es üòÉN&#39;h√©sitez pas √† nous relancer si vous n&#39;avez pas eu de nouvelles apr√®s une semaine !</description>
    </item>
    
  </channel>
</rss>
